// cycle :: Iterable -> ReadableStream
// cycle function takes an iterable
// as argument and returns a readable stream
// that repeatedly emits values generated by the emitter.
//

import Pipe from "@pipes/core/pipe";

export default function cycle( iterator ) {

  // Check if not iterator
  if ( !iterator[Symbol.iterator] ) {
    iterator = [ iterator ];
  }

  let
  { readable, writable } = new Pipe( function* () {
    while ( true ) {
      yield* iterator;
    }
  }, { init: null });

  return readable;
}

// Browserify compat
if ( typeof module !== "undefined" )
  module.exports = cycle;



